# Generated by Django 2.2.4 on 2019-09-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_relator_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha boleta')),
                ('total', models.IntegerField(verbose_name='Total boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre juguete')),
                ('precio', models.IntegerField(blank=True, null=True, verbose_name='Precio juguete')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad juguete')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Cantidad juguete')),
            ],
        ),
    ]
