# Generated by Django 2.2.4 on 2019-09-12 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_boleta_juguete'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='juguete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.Juguete'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha boleta'),
        ),
    ]
