# Generated by Django 2.2.4 on 2019-09-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20190912_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relator',
        ),
    ]
