# Generated by Django 2.2.6 on 2019-10-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imagefile',
            new_name='imageFile',
        ),
    ]
