# Generated by Django 2.2.6 on 2019-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20191008_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='imageFile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
