# Generated by Django 2.2.4 on 2019-09-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_delete_relator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion'),
        ),
    ]
